projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('detail/<int:pk>/', views.project_detail, name='project_detail'),
    path('create/', views.project_create, name='project_create'),
    path('update/<int:pk>/', views.project_update, name='project_update'),
    path('delete/<int:pk>/', views.project_delete, name='project_delete'),
]

source/urls.py
from django.contrib import admin
from django.urls import include, path
from todo import views as todo_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',todo_views.home, name='home'), 
    path('todo/', include('todo.urls')),  
    path('accounts/', include('accounts.urls')),
    path('projects/',include('projects.urls')), 
]

todo/urls.py
from django.urls import path
from . import views
from .views import   TaskListView
app_name = 'todo'
urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('create/', views.task_create, name='task-create'),
    path('update/<int:pk>/',views.task_update, name='task-update'),
    path('delete/<int:pk>/', views.task_delete, name='task-delete'),
    path('detail/<int:pk>',views.task_detail, name='task-detail'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    members = models.ManyToManyField(User, related_name='projects')

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'members']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'members': forms.SelectMultiple(attrs={'class': 'form-control'}) 
        }

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

from todo.models import Project
from .forms import ProjectForm

@login_required
def project_create(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.created_by = request.user  
            project.save()
            form.save_m2m() 
            messages.success(request, 'Project created successfully!')
            return redirect('project_list')
    else:
        form = ProjectForm()
    return render(request, 'projects/project_form.html', {'form': form})

@login_required
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    tasks = project.tasks.all()
    return render(request, 'projects/project_detail.html', {'project': project, 'tasks': tasks})


def project_list(request):
    projects = Project.objects.all()
    paginate_by = 5
    paginate_orphans = 1
    return render(request, 'projects/project_list.html', {'projects': projects})
@login_required
def project_update(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            project = form.save()
            messages.success(request, 'Project updated successfully!')
            return redirect('project_list')
    else:
        form = ProjectForm(instance=project)

    return render(request, 'projects/project_form.html', {'form': form})

@login_required
def project_delete(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        project.delete()
        messages.success(request, 'Project deleted successfully!')
        return redirect('project_list')

    return render(request, 'projects/project_confirm_delete.html', {'project': project})

templates/projects/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Удаление проекта "{{ object.name }}"</h2>
    <p>Вы уверены, что хотите удалить этот проект?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'projects:project_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

templates/projects/project_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ project.name }}</h2>
    <p>{{ project.description }}</p>
    <p>Created at: {{ project.created_at }}</p>
    <h3>Задачи проекта</h3>
    <ul>
        {% for task in tasks %}
            <li>
                <a href="{% url 'todo:task-detail' task.pk %}">{{ task.title }}- {{ task.status }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'projects:project_update' project.pk %}" class="btn btn-secondary">Редактировать</a>
    <a href="{% url 'projects:project_delete' project.pk %}" class="btn btn-danger">Удалить</a>
{% endblock %}

templates/projects/project_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>{% if form.instance.pk %}Редактирование проекта{% else %}Создание проекта{% endif %}</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

templates/projects/project_list.html
{% extends 'base.html' %}

{% block content %}
    <h2>Проекты</h2>
    <a href="{% url 'projects:project_create' %}" class="btn btn-primary">Создать проект</a>
    <ul class="list-group mt-3">
        {% for project in projects %}
            <li class="list-group-item">
                <a href="{% url 'projects:project_detail' project.pk %}">{{ project.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% include 'partials/pagination.html' %}
{% endblock %}
    