source/urls.py
from django.contrib import admin
from django.urls import include, path
from todo import views as todo_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',todo_views.home, name='home'), 
    path('todo/', include('todo.urls')),  
    path('accounts/', include('accounts.urls')),
    path('projects/',include('projects.urls')), 
]

todo/urls.py
from django.urls import path
from . import views
from .views import   TaskListView
app_name = 'todo'
urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('create/', views.task_create, name='task-create'),
    path('update/<int:pk>/',views.task_update, name='task-update'),
    path('delete/<int:pk>/', views.task_delete, name='task-delete'),
    path('detail/<int:pk>',views.task_detail, name='task-detail'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

from projects.models import Project

class Task(models.Model):
    STATUS_CHOICES = (
        ('in progress', 'In Progress'),
        ('completed', 'Completed'),
        ('pending', 'Pending'),
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    users = models.ManyToManyField(User, related_name='tasks', blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks',default=None)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Task
from django.db.models import Q

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Title'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'project': forms.Select(attrs={'class': 'form-control'})  
        }
        
class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')

class TaskFilterForm(forms.Form):
    status = forms.ChoiceField(choices=[('', 'All'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], required=False)
    created_at = forms.DateField(input_formats=['%b %d %Y'], required=False, error_messages={'invalid': 'Enter a date like this: Mon DD YYYY'})
    search = forms.CharField(max_length=100, required=False)

    def filter_queryset(self, queryset):
        query = Q()
        if self.is_valid():
            status = self.cleaned_data['status']
            if status:
                query &= Q(status=status)
            created_at = self.cleaned_data['created_at']
            if created_at:
                query &= Q(created_at__date=created_at)
            search = self.cleaned_data['search']
            if search:
                query &= Q(title__icontains=search) | Q(description__icontains=search)
        return queryset.filter(query)

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse, reverse_lazy
from todo.forms import TaskFilterForm, TaskForm,SearchForm
from todo.models import Task 
from django.views.generic import ListView, DetailView, DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
def home(request):
    return render(request, 'home.html')
@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:task-list')  
    else:
        form = TaskForm()
    return render(request, 'todo/task_form.html', {'form': form})
class TaskListView(ListView):
    model= Task
    template_name = 'task_list.html'
    form = SearchForm
    paginate_by = 5
    paginate_orphans = 1
    search_value = None 
    def get_queryset(self):
        queryset = super().get_queryset()
        form = TaskFilterForm(self.request.GET)
        if form.is_valid():
            queryset = form.filter_queryset(queryset)
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TaskFilterForm(self.request.GET)
        return context
# class TaskUpdateView(LoginRequiredMixin, UpdateView):
#     model = Task
#     form_class = TaskForm
#     template_name = 'task_form.html'

#     def get_object(self, queryset=None):
#         obj = super().get_object(queryset)
#         if self.request.user not in obj.users.all():
#             raise PermissionDenied
#         return obj

#     def get_success_url(self):
#         return reverse('todo:task-detail', kwargs={'pk': self.object.pk})
def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            messages.success(request, 'Task updated successfully!')
            return redirect('todo:task-list')
    else:
        form = TaskForm(instance=task)

    return render(request, 'todo/task_form.html', {'form': form})

# class TaskDeleteView(LoginRequiredMixin,DeleteView):
#     model = Task
#     template_name = 'task_delete.html'
#     def get_queryset(self):
#         return super().get_queryset().filter(users=self.request.user)

#     def get_success_url(self):
#         return reverse_lazy('task-list')
# class TaskDetailView(LoginRequiredMixin,DetailView):
#     model = Task
#     template_name = 'task_detail.html'
#     context_object_name = 'task'
#     def get_queryset(self):
#         return super().get_queryset().filter(users=self.request.user)
@login_required
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        task.delete()
        messages.success(request, 'Task deleted successfully!')
        return redirect('todo:task_list')
    return render(request, 'todo/task_delete.html', {'task': task})
def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    return render(request, 'todo/task_detail.html', {'task': task})

templates/todo/task_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h1> Confirm deletion of a task</h1>
    <p>Are you sure you want to delete the task "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/todo/task_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h5 class="card-title"> {{ task.title }}</h5>
    <p><strong>Title:</strong> {{ task.description }}</p>
    <p><strong>Status:</strong> {{ task.status }}</p>
    <p><strong>Creation date:</strong> {{ task.created_at }}</p>    
    <a href="{% url 'todo:task-update' pk=task.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'todo:task-delete' pk=task.pk %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Back to list</a>
</div>
{% endblock %}

templates/todo/task_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>{% if form.instance.pk %}Редактирование задачи{% else %}Создание задачи{% endif %}</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

templates/todo/task_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Tasks List</h1>
<form method="get">

    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">search</button>
    </form>
    <form id="search-form" method="get">
       </form>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Desription</th>
            <th scope="col">Status</th>
            <th scope="col">Creation date</th>
            <th scope="col">Task for</th>
        </tr>
        
    </thead>
    <tbody>
        {% for task in object_list  %}
        <tr>
            <td>{{ task.title }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.status }}</td>
            <td>{{ task.created_at }}</td>
            <td>
                {% for user in task.users.all %}
                    {{ user.get_full_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td><a href="{% url 'todo:task-detail' pk=task.pk %}" class="btn btn-primary">more</a></td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
{% include 'partials/pagination.html' %}
{% endblock %}