accounts/urls.py
from django.urls import path
from accounts.views import login_view,logout_view,RegisterView,create_profile
from .views import profile, change_password
app_name = 'accounts'
urlpatterns = [
    path('profile/', profile, name='profile'),
    path('create/', create_profile, name='create_profile'),
    path('change_password/', change_password, name='change_password'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('detail/<int:pk>/', views.project_detail, name='project_detail'),
    path('create/', views.project_create, name='project_create'),
    path('update/<int:pk>/', views.project_update, name='project_update'),
    path('delete/<int:pk>/', views.project_delete, name='project_delete'),
]

source/urls.py
from django.contrib import admin
from django.urls import include, path
from todo import views as todo_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',todo_views.home, name='home'), 
    path('todo/', include('todo.urls')),  
    path('accounts/', include('accounts.urls')),
    path('projects/',include('projects.urls')), 
]

todo/urls.py
from django.urls import path
from . import views
from .views import   TaskListView
app_name = 'todo'
urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('create/', views.task_create, name='task-create'),
    path('update/<int:pk>/',views.task_update, name='task-update'),
    path('delete/<int:pk>/', views.task_delete, name='task-delete'),
    path('detail/<int:pk>',views.task_detail, name='task-detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Management</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Project Management</a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'projects:project_list' %}">Projects</a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:task-list' %}">Task list</a> 
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'projects:project_create' %}">Create Project</a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:task-create' %}">Create Task</a> 
                </li>
                {% endif %}
            </ul><ul class="navbar-nav ml-auto">               
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.get_full_name|default:request.user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:profile' %}">Account</a>
                            <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добро пожаловать на Todoist</title>
    <style>
        img {
            max-width: 90%;
            height: auto;
        }
    </style>
</head>
<body>
 <img src="https://cdn-aicin.nitrocdn.com/HIAjYmsdLpRQdKpIMJLXFmZsSAYnEnkl/assets/images/optimized/rev-57f6fb0/www.amitree.com/wp-content/uploads/2021/08/the-pros-and-cons-of-paper-to-do-lists.jpeg" alt="To Do List"> 
</body>
</html>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo list</title>
    <div class="container">
        <h1>WELCOME to our Todo List app!</h1>
     </div>
</head>
{% endblock %}